description_TTT<-function(){
cat("******************************************************************************\n")
cat("                      Two-Times-Tmax (TTT) method                             \n")
cat("------------------------------------------------------------------------------\n")
cat(" The TTT method is based on the Bateman function.  The Bateman function       \n")
cat(" has two outstanding points.  First, the maximum of the curve (Cmax at        \n")
cat(" Tmax) and secondly, the inflection point of the curve (Cinpt at Tinpt).      \n")
cat(" The inflection point of the curve describes the point where the algebraic    \n")
cat(" sign of the curvature changes. Tinpt is equal to two times Tmax.  Thus,      \n")
cat(" The twofold of the observed Tmax value can be used as a threshold of time    \n")
cat(" points to be included in the calculation of lambda_z.                       \n")
cat(" Ref.:Scheerans C, Derendorf H and C Kloft. Proposal for a Standardised       \n")
cat("      Identification of the Mono-Exponential Terminal Phase for Orally        \n")
cat("      Administered Drugs. Biopharm Drug Dispos 29, 145-157 (2008).            \n")
cat("******************************************************************************\n")
cat("\n")
}