description_pointselect<-function(){
cat("\n\n")
cat("*******************************************************************************\n")
cat("                     Point Selection for Lambda_z Estimation                   \n")
cat("-------------------------------------------------------------------------------\n")
cat(" This method is about to select data points for lambda_z estimation based on   \n")
cat(" the manual selection from each subject's log(conc.) vs. time plot. Please     \n")
cat(" use your mouse to click the data point on the graph to select the data        \n")
cat(" points for linear regression. Once you want to stop selection for each plot,  \n")
cat(" click the 'Stop' menu on the left corner of th plot and click 'Stop locator.' \n")
cat(" When finishing the current subject and the next subject's plot will show up.  \n")
cat(" Do the same procedurs until finishing all subjects.                         \n\n")
cat(" Note: The # of data points should be at least 2's and max. is 6.              \n")
cat("       Please do NOT choose any data point before Tmax.                        \n")
cat("*******************************************************************************\n")
cat("\n\n")
alarm();alarm()
readline("  Press Enter to continue...")
}