description_version<-function(){
cat("~~~  This report is generated by bear v2.1.0 for R ~~~\n")
cat("Authors: Hsin-ya Lee, Yung-jin Lee\n")
cat("#100, Shih-chuan 1st Rd.\n")
cat("College of Pharmacy,\n")
cat("Kaohsiung Medical University,\n")
cat("Kaoshiung, Taiwan 80708\n")
cat("E-mail: hsinyalee@gmail.com,\n")
cat("        pkpd.taiwan@gmail.com \n")
cat("bear's website: http://pkpd.kmu.edu.tw/bear\n")
cat("R website: www.r-project.org\n")
cat("---------------------------------------------------\n")
}