.First.lib <- function(...) {

# echo output to screen
cat("\n")
cat("\n")
cat("***********************************************************************\n")
cat("*                                                                     *\n")
cat("*                                  bear                               *\n")
cat("*                                v 1.1.3                              *\n")   
cat("*                    http://pkpd.kmu.edu.tw/bear                      *\n")
cat("*                                                                     *\n")
cat("* This package is designed to analyze average bioequivalence (ABE)    *\n")
cat("* (NCA -> ANOVA) or bioavailability (NCA only) data, with study       *\n")
cat("* design of a standard RT/TR 2-treatment, 2-sequence, and 2-period,   *\n")
cat("* balanced, crossover design.  Currently, it should NOT be used to    *\n")
cat("* analyze imbalanced, replicated ABE study.                           *\n")
cat("*                                                                     *\n")
cat("* bear contains three independent data analysis procedures:           *\n")
cat("*   1. Sample size estimation for ABE (mean ratio)                    *\n")
cat("*   2. Noncompartmental Analysis (NCA)                                *\n")
cat("*   3. ANOVA (using 'lm' in R)                                        *\n")
cat("*                                                                     *\n")
cat("*                   Please type 'go()' to get started.                *\n")
cat("*                                                                     *\n")
cat("***********************************************************************\n")
}
